site_name: "LanguageAssistant"
repo_url: https://github.com/dagleaves/languageassistant

theme:
  name: readthedocs

nav:
  - 'Getting Started':
      - Introduction: 'index.md'
      - user_guide.md
  - 'Modules':
      - 'Agents':
          - modules/agents/conversation.md
          - modules/agents/planner.md
      - modules/transcriber.md
      - modules/tts.md
  - 'About':
      - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

watch:
  - languageassistant

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_source: false
            show_submodules: true
