name: 'Setup Python + Poetry environment'
description: 'Setup Python + Poetry environment'

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.10'
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: portaudio19-dev python-pyaudio
        version: 1.0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}
    - name: Install poetry
      run: python -m pip install poetry
      shell: bash
    - name: Create virtual environment
      run: poetry install
      shell: bash
